dj_portfolio/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from dj_portfolio import views

app_name='portfolio'
urlpatterns = [
    # portfolio CRUD
    path('create/', views.PortfolioCreate.as_view(), name='portfolio-create'),
    path('', views.PortfolioList.as_view(), name='portfolio-list'),
    path('<int:pk>/', views.PortfolioDetail.as_view(), name='portfolio-detail'),
    path('<pk>/update', views.PortfolioUpdate.as_view(), name='portfolio-update'),
    path('<pk>/delete', views.PortfolioDelete.as_view(), name='portfolio-delete'),

    path('<pk>/value', views.get_portfolio_value, name='portfolio-value'),
    path('<pk>/sector', views.get_sector_balance, name='portfolio-sector'),

    path('<pk>/sector-comp/<sector>', views.sector_comp, name='sector-comp'),
    path('<pk>/sector-comp-data/<sector>', views.sector_comp_data, name='sector-comp-data'),
    
    # helper
    path('add-holding', views.PortfolioAddHolding, name='portfolio-add-holding'),

    # holding CRUD
    path('holding/create/', views.HoldingCreate.as_view(), name='holding-create'),
    path('holding/all/', views.HoldingList.as_view(), name='holding-list'),
    path('holding/<pk>/', views.HoldingDetail.as_view(), name='holding-detail'),
    path('holding/<pk>/update', views.HoldingUpdate.as_view(), name='holding-update'),
    path('holding/<pk>/delete', views.HoldingDelete.as_view(), name='holding-delete'),

    # stock
    path('stock/create/', views.StockCreate.as_view(), name='stock-create'),
    path('stock/all/', views.StockList.as_view(), name='stock-list'),
    path('stock/<pk>/', views.StockDetail.as_view(), name='stock-detail'),
    path('stock/<pk>/update', views.StockUpdate.as_view(), name='stock-update'),
    path('stock/<pk>/delete', views.StockDelete.as_view(), name='stock-delete'),

    path('stocky/get-price/', views.get_stock_price, name='get-stock-price'),

]

dj_portfolio/templates/dj_portfolio/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}{% endblock %}</title>

    
    <!--Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    {% block head %}
    {% endblock %}
  </head>
  
  <body>

    <nav class="navbar sticky-top navbar-light" style="background-color: #e3f2fd;">
      <a class="navbar-brand" href="{% url 'portfolio:portfolio-list' %}">Portfolio</a>
    </nav>
    <div class="container">
      {% block content %}{% endblock %}
    </div>


    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>


</html>

dj_portfolio/templates/dj_portfolio/holding_confirm_delete.html
{% extends 'dj_portfolio/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
	<form method="post">{% csrf_token %} 
	  <p>Are you sure you want to delete "{{ object }}"?</p> 
	  <input type="submit" value="Confirm">
	</form>
      </div>
    </div>
{% endblock %} 

dj_portfolio/templates/dj_portfolio/holding_detail.html
{% extends 'dj_portfolio/base.html' %}

{% block content %}
  <h1>{{ object.name }}</h1>

  <table class="table">
    <tr>
      <td>Portfolio</td>
      <td>{{ object.portfolio }}</td>
    </tr>
    
    <tr>
      <td>Ticker</td>
      <td>{{ object.ticker }}</td>
    </tr>
    <tr>
      <td>Shares</td>
      <td>{{ object.quantity }}</td>
    </tr>
  </table>
  
   
{% endblock %}

dj_portfolio/templates/dj_portfolio/holding_form.html
{% extends 'dj_portfolio/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <hr class="mt-0 mb-4">
	<form method="POST" enctype="multipart/form-data">  
	  {% csrf_token %} 
	  
	  {{ form|crispy}} 
	  
	  <input type="submit" value="Submit" class="btn btn-success">
	</form>
      </div>
    </div>
  </div>
{% endblock %}

dj_portfolio/templates/dj_portfolio/holding_list.html
{% extends 'dj_portfolio/base.html' %}

{% block title %}Holdings{% endblock %}
{% block content %}
  <h1>Holdings</h1>
  {% for holding in object_list %}
    <li>{{ holding }}</li>
  {% empty %}
    <p>You have not created any holdings!</p>
  {% endfor %}
  
{% endblock %}

dj_portfolio/templates/dj_portfolio/index.html
{% extends 'dj_portfolio/base.html' %}

{% block title %}Portfolio{% endblock %}
{% block content %}
  <h1>Portfolios</h1>
  
  {% for portfolio in portfolios %}
    <li><a href={% url 'portfolio:portfolio-detail' pk=portfolio.id %}>{{ portfolio.name }}</a></li>
  {% empty %}
    <p>You have not created any portfolios yet!</p>
  {% endfor %}
  
{% endblock %}

dj_portfolio/templates/dj_portfolio/portfolio_detail.html
{% extends 'dj_portfolio/base.html' %}

{% block head %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.28.0/moment.min.js" integrity="sha512-Q1f3TS3vSt1jQ8AwP2OuenztnLU6LwxgyyYOG1jgMW/cbEMHps/3wjvnl1P3WTrF3chJUWEoxDUEjMxDV8pujg==" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.3.0/Chart.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>



{% endblock %}
{% block title %}
  {{ object.name }}
{% endblock %}

{% block content %}
  <h1>{{ object.name }}</h1>

  <!-- <h3>Value: {{ object.display_value }}</h3> -->
  <div class="row">
    <div class="col-sm">
      <h3>Div Yield:
	<p>{{ object.div }}</p></h3>
    </div>
    <div class="col-sm">
      <h3 id="daychange">Day Value Change: </h3>
    </div>
  </div>
  <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Add Holding</button>

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
      
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
	  <button type="button" class="close" data-dismiss="modal">&times;</button>
	  <h4 class="modal-title">Add Holding</h4>
        </div>
        <div class="modal-body">
	  {% csrf_token %} 
	  {{ holdingForm.as_p }}
        </div>
        <div class="modal-footer">
	  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	  <button type="button" id="saveHolding" class="btn btn-success">Save</button>
        </div>
      </div> 
    </div>
  </div>
  <hr>

  {% if object.holding_set.all %}
    <div class="row">
      <div class="col-sm">
	<input id="start" type="date" class="form-control" value="{{ start }}">
      </div>
      <div class="col-sm">
	<button type="button" class="btn btn-primary" onclick="makeValueChart()">Update Chart</button>
      </div>
    </div>
    <h3>Performance
    <div id="valChartWrapper">
      <canvas id="valChart"></canvas>
    </div>
    <h3>Composition</h3>
    <canvas id="sectChart"></canvas>
  {% endif  %}
  
  {% if object.holding_set.all %}
    <h3>Holdings</h3>
    <table id="holdings" class="table">
      <thead>
	<th>Stock</th>
	<th>Price</th>
	<th>% Day Change</th>
	<!-- <th>Quantity</th> -->
	<!-- <th>Value</th> -->
	<th>Share</th>
	<th>Dividend</th>
	<th>Sector</th>
	<th>Actions</th>
      </thead>
      <tbody>
	{% for holding in object.holding_set.all %}
	  <tr>
	    <td><a href="{% url 'portfolio:stock-detail' pk=holding.stock.pk %}">{{ holding.stock.name }} ({{ holding.stock.ticker }})</a></td>
	    <td>{{ holding.stock.price }}</td>
	    <td>{{ holding.stock.price_change }}</td>
	    <!-- <td>{{ holding.quantity }}</td> -->
	    <!-- <td>{{ holding.display_value }}</td> -->
	    <td>{{ holding.display_share }}</td>
	    <td>{{ holding.stock.div }}</td>
	    <td><a href="{% url 'portfolio:sector-comp' pk=object.id sector=holding.stock.sector_slug %}">{{ holding.stock.sector }}</a></td>
	    <td><a href="{% url 'portfolio:holding-update' pk=holding.id %}">Edit</a> <a href="{% url 'portfolio:holding-delete' pk=holding.id %}">Delete</a></td>
	    <td display="none">{% if holding.stock.clean200 %}Clean200{% endif %}</td>
	  </tr>
	{% endfor %}

      </tbody>
    </table>
  {% endif %}

  
  <script>

  </script>
  
  
  <script>
   $(document).ready(function(){
       $('#holdings').DataTable({
	   "order":[[3, "desc"]],
	   "columnDefs": [
	       {
		   "targets": [7],
		   "visible": false,
		   "searchable": true
	       },
	   ]
       })
       makeValueChart()
       makeSectorChart()
   })


   function makeValueChart() {

       $('#valChart').remove();
       $('#valChartWrapper').append('<canvas id="valChart"></canvas>')
       
       var _labels = [];
       var _port;
       var _voo;
       
       $.ajax({
	   url: "{% url 'portfolio:portfolio-value' pk=object.pk%}",
	   type: "get",
	   data: {"start": $("#start").val()},
	   success: function(d) {
	       // display errors
	       if(d.msg){
		   $('#dateError').remove()
		   $('#valChartWrapper').prepend('<div id="dateError" class="alert alert-danger">'+d.msg+'</div>');
	       }

	       _port = d.port;
	       _sp500 = d.sp500;
	       _labels = d.index;

	       day_ch = ((d.port[d.port.length -1] / d.port[d.port.length -2] -1)* 100).toFixed(2)
	       
	       if (day_ch >= 0) {
		   $("#valch").remove()
		   $('#daychange').append('<p id="valch" style="color:green">' + day_ch + '%' + '</p>');
	       }
	       if (day_ch < 0) {
		   $("#valch").remove()
		   $('#daychange').append('<p id="valch" style="color:red">' + day_ch + '%' + '</p>');
	       }

	       // make chart
	       var ctx = document.getElementById('valChart').getContext('2d'); 
	       var chart = new Chart(ctx, {
		   type: 'line',
		   data: {
		       labels: _labels,
		       datasets: [
			   {label: 'Portfolio',
			    backgroundColor: '#f08080',
			    borderColor: '#f08080',
			    fill: false,
			    data: _port,
			   },
			   {label: 'S&P 500',
			    backgroundColor: '#d1eeee',
			    borderColor: '#d1eeee',
			    fill: false,
			    data: _sp500,
			   }
		       ]
		   },
		   options: {
		       scales: {
			   xAxes: [{
			       type: 'time',
			       time: {
				   tooltipFormat: 'MM/DD/YYYY',
			       }

			   }]
		       }
		   }
	       })
	   }
       })
       
   }
   
   function makeSectorChart() {
       var labels = []
       
       $.ajax({
	   url: "{% url 'portfolio:portfolio-sector' pk=object.pk %}",
	   type: "get",
	   success: function(d) {

	       labels = d.labels;

	       var ctx = document.getElementById('sectChart').getContext('2d');

	       var myDoughnutChart = new Chart(ctx, {
		   type: 'doughnut',
		   data: {
		       datasets: [{
			   data: d.data,
			   backgroundColor: ["#0074D9", "#FF4136", "#2ECC40", "#FF851B", "#7FDBFF", "#B10DC9", "#FFDC00", "#001f3f", "#39CCCC", "#01FF70", "#85144b", "#F012BE", "#3D9970", "#111111", "#AAAAAA"]
			   
		       }],
		       labels: labels
		       
		   }
	       })
	   }
       })
   };
   
   $('#saveHolding').click(function(){
       newHolding();
   });

   function newHolding(){
       $("#myModal").modal('hide')
       
       $.post("{% url 'portfolio:portfolio-add-holding' %}",
	      {csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(),
	       portfolio: {{ object.id }},
	       stock: $("input[name=stock]").val(),
	       quantity: $("input[name=quantity]").val()
	      })
		    .done(function(msg){
			location.reload()
		    })
   };

   
   
  </script>

  
{% endblock %}

dj_portfolio/templates/dj_portfolio/portfolio_form.html
{% extends 'dj_portfolio/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <hr class="mt-0 mb-4">
	<form method="POST" enctype="multipart/form-data">  
	  {% csrf_token %} 
	  
	  {{ form|crispy}} 
	  
	  <input type="submit" value="Submit" class="btn btn-success">
	</form>
      </div>
    </div>
  </div>
{% endblock %}

dj_portfolio/templates/dj_portfolio/portfolio_list.html
{% extends 'dj_portfolio/base.html' %}

{% block title %}Portfolio{% endblock %}
{% block content %}
  <h1>Portfolios</h1>
  <a href="{% url 'portfolio:portfolio-create' %}" class="btn btn-primary">New Portfolio</a>
  {% for portfolio in object_list %}
    <li><a href={% url 'portfolio:portfolio-detail' pk=portfolio.id %}>{{ portfolio.name }}</a></li>
  {% empty %}
    <p>You have not created any portfolios yet!</p>
  {% endfor %}
  
{% endblock %}

dj_portfolio/templates/dj_portfolio/sector.html
{% extends 'dj_portfolio/base.html' %}

{% block head %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.28.0/moment.min.js" integrity="sha512-Q1f3TS3vSt1jQ8AwP2OuenztnLU6LwxgyyYOG1jgMW/cbEMHps/3wjvnl1P3WTrF3chJUWEoxDUEjMxDV8pujg==" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.3.0/Chart.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>



{% endblock %}
{% block title %}
  {{ sector }}
{% endblock %}

{% block content %}
  <h1>{{ sector }}</h1>

  <div class="row">
    <div class="col-sm">
      <input id="start" type="date" class="form-control" value="{{ start }}">
    </div>
    <div class="col-sm">
      <button type="button" class="btn btn-primary" onclick="makeValueChart()">Update Chart</button>
    </div>
  </div>
  
  <h3>Performance
    <div id="valChartWrapper">
      <canvas id="valChart"></canvas>
    </div>
    
    <h3>Holdings</h3>
    <table id="holdings" class="table">
      <thead>
	<th>Stock</th>
	<th>Price</th>
	<th>% Day Change</th>
	<!-- <th>Quantity</th> -->
	<!-- <th>Value</th> -->
	<th>Share</th>
      </thead>
      <tbody>
	{% for holding in portfolio.holding_set.all %}
	  {% if holding.stock.sector == sector %}
	    <tr>
	      <td><a href="{% url 'portfolio:stock-detail' pk=holding.stock.pk %}">{{ holding.stock.name }} ({{ holding.stock.ticker }})</a></td>
	      <td>{{ holding.stock.price }}</td>
	      <td>{{ holding.stock.price_change }}</td>
	      <!-- <td>{{ holding.quantity }}</td> -->
	      <!-- <td>{{ holding.display_value }}</td> -->
	      <td>{{ holding.display_share }}</td>
	    </tr>
	  {% endif %}
	{% endfor %}

      </tbody>
    </table>
    
    </script>
    
    
    <script>
     $(document).ready(function(){
	 $('#holdings').DataTable({
	     "order":[[3, "desc"]],

       })
       makeValueChart()
   })


   function makeValueChart() {

       $('#valChart').remove();
       $('#valChartWrapper').append('<canvas id="valChart"></canvas>')
       
       var _labels = [];
       var _port;
       var _voo;
       
       $.ajax({
	   url: "{% url 'portfolio:sector-comp-data' pk=portfolio_id sector=sector_slug %}",
	   type: "get",
	   data: {"start": $("#start").val()},
	   success: function(d) {
	       // display errors
	       if(d.msg){
		   $('#dateError').remove()
		   $('#valChartWrapper').prepend('<div id="dateError" class="alert alert-danger">'+d.msg+'</div>');
	       }

	       _port = d.port;
	       _sp500 = d.sp500;
	       _labels = d.index;

	       day_ch = ((d.port[d.port.length -1] / d.port[d.port.length -2] -1)* 100).toFixed(2)
	       
	       if (day_ch >= 0) {
		   $("#valch").remove()
		   $('#daychange').append('<p id="valch" style="color:green">' + day_ch + '%' + '</p>');
	       }
	       if (day_ch < 0) {
		   $("#valch").remove()
		   $('#daychange').append('<p id="valch" style="color:red">' + day_ch + '%' + '</p>');
	       }

	       // make chart
	       var ctx = document.getElementById('valChart').getContext('2d'); 
	       var chart = new Chart(ctx, {
		   type: 'line',
		   data: {
		       labels: _labels,
		       datasets: [
			   {label: 'Portfolio',
			    backgroundColor: '#f08080',
			    borderColor: '#f08080',
			    fill: false,
			    data: _port,
			   },
			   {label: 'S&P 500',
			    backgroundColor: '#d1eeee',
			    borderColor: '#d1eeee',
			    fill: false,
			    data: _sp500,
			   }
		       ]
		   },
		   options: {
		       scales: {
			   xAxes: [{
			       type: 'time',
			       time: {
				   tooltipFormat: 'MM/DD/YYYY',
			       }

			   }]
		       }
		   }
	       })
	   }
       })
     };
   
		 
    </script>

    
{% endblock %}

dj_portfolio/templates/dj_portfolio/stock_detail.html
{% extends "dj_portfolio/base.html" %}
{% block title %}Portfolio{% endblock %}
{% block head %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.28.0/moment.min.js" integrity="sha512-Q1f3TS3vSt1jQ8AwP2OuenztnLU6LwxgyyYOG1jgMW/cbEMHps/3wjvnl1P3WTrF3chJUWEoxDUEjMxDV8pujg==" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.3.0/Chart.min.js"></script>

  {{ divs_chart|json_script:"divs-data" }}
{% endblock %}

{% block content %}
  <h1>{{ object.name }}</h1>
  <h4>{{ object.sector }} | {{ object.industry }}</h4>
  {% if object.clean200 %}
    <h5>Clean 200 Company</h5>
  {% endif %}

  <h3 id="daychange">Day Value Change: </h3>

  <div class="row">
    <div class="col-sm">
      <input id="start" type="date" class="form-control" value="{{ start }}">
    </div>
    <div class="col-sm">
      <button type="button" class="btn btn-primary" onclick="stockPriceChart()">Update Chart</button>
    </div>
  </div>
  <canvas id="priceChart"></canvas>

  <h4>Summary</h4>
  <p>{{ object.summary }}</p>
  
  <h4>Dividends</h4>
  <div class="row">
    <div class="col-sm">
      Yield: {{ object.div }}
    </div>
    <div class="col-sm">
      Payout Ratio: {{ object.payoutRatio }}
    </div>  
  </div>

  <canvas id="divChart"></canvas>
  {{ divs | safe }}

  
  <script>
   
   $(document).ready(function(){
       stockPriceChart()
       stockDivChart()
   })

   function stockPriceChart(){
       var _labels = [];
       var _data;
       
       $.ajax({
	   url: "{% url 'portfolio:get-stock-price' %}",
	   type: "get",
	   data: {ticker: "{{ object.ticker }}",
		  start: $("#start").val()},
	   success: function(d) {
	       
	       _data = d.data;
	       _labels = d.index;

	       day_ch = ((_data[_data.length -1] - _data[_data.length -2])/_data[_data.length -2]*100).toFixed(2)
	       
	       if (day_ch >= 0) {
		   $("#valch").remove()
		   $('#daychange').append('<p id="valch" style="color:green">' + day_ch + '%' + '</p>');
	       }
	       if (day_ch < 0) {
		   $("#valch").remove()
		   $('#daychange').append('<p id="valch" style="color:red">' + day_ch + '%' + '</p>');
	       }

	       
	       var ctx = document.getElementById('priceChart').getContext('2d'); 
	       var chart = new Chart(ctx, {
		   type: 'line',
		   data: {
		       labels: _labels,
		       datasets: [
			   {label: 'Price',
			    backgroundColor: '#f08080',
			    borderColor: '#f08080',
			    fill: false,
			    data: _data,
			   }
		       ]
		   },
		   options: {
		       scales: {
			   xAxes: [{
			       type: 'time',
			       time: {
				   tooltipFormat: 'MM/DD/YYYY',
			       }
			   }]
		       }
		   }
	       })
	   }
       })       
   }

   function stockDivChart(){

       const divs = JSON.parse(document.getElementById('divs-data').textContent);
       
       var ctx = document.getElementById('divChart').getContext('2d'); 
       var chart = new Chart(ctx, {
	   type: 'line',
	   data: {
	       labels: divs.index,
	       datasets: [
		   {label: 'Dividends',
		    fill: false,
		    data: divs.data,
		   }
	       ]
	   },
	   options: {
	       scales: {
		   xAxes: [{
		       type: 'time',
		       time: {
			   tooltipFormat: 'MM/DD/YYYY',
		       }
		   }]
	       }
	   }
       })
   }
   
  </script>
  
{% endblock %}

dj_portfolio/templates/dj_portfolio/stock_form.html
{% extends 'dj_portfolio/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <hr class="mt-0 mb-4">
	<form method="POST" enctype="multipart/form-data">  
	  {% csrf_token %} 
	  
	  {{ form|crispy}} 
	  
	  <input type="submit" value="Submit" class="btn btn-success">
	</form>
      </div>
    </div>
  </div>
{% endblock %}